language: python

python:
  - "2.6"
  - "2.7"

script:
  - coverage run $(which nose2)
  - flake8 hyperkit

after_success:
  - coveralls

notifications:
  irc: "irc.oftc.net#yaybu"
  on_success: change
  on_failure: always

