language: python

python:
  - "2.6"
  - "2.7"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --allow-external argparse --allow-unverified argparse 'argparse>=1.2.1,<1.3'; fi
  - pip install -r requirements.txt

script:
  - coverage run $(which nose2)
  - flake8 hyperkit

after_success:
  - coveralls

notifications:
    irc: 
        channels:
          - "irc.oftc.net#yaybu"
        use_notice: true
        skip_join: true
        on_success: change
        on_failure: always

